#{doctype, title, html, head, body, script, span, div, style, h1, h2, h3, ul, li, dl, dd, dt, table, tr, thead, td, th, tbody, tfoot, colgroup, input, text} = gen.dk
doctype_ = gen.dk.doctype
title_ = gen.dk.title
html_ = gen.dk.head
head_ = gen.dk.head
body_ = gen.dk.body
script_ = gen.dk.script
span_ = gen.dk.span
div_ = gen.dk.div
style_ = gen.dk.style
h1_ = gen.dk.h1
text_ = gen.dk.text
input_ = gen.dk.input
p_ = gen.dk.p
